spring:
  application:
    name: animals
  datasource:
    url: jdbc:mysql://localhost:3306/animals_db?useSSL=false&allowPublicKeyRetrieval=true
    username: igor
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect